name: ci

on:
  push:
    branches:
      - "main"
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ "buster", "bullseye" ]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2

      - run: curl -sSLf https://raw.githubusercontent.com/octohelm/dagger/main/install.sh | sudo sh

      - run: make ship.${{ matrix.version }}
        env:
          DAGGER_LOG_FORMAT: plain
          GH_USERNAME: ${{ github.actor }}
          GH_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          GIT_SHA: ${{ github.sha }}
          GIT_REF: ${{ github.ref }}
