name: ci

on:
  push:
    branches:
      - "main"
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DAGGER_LOG_FORMAT: plain
      GH_USERNAME: ${{ github.actor }}
      GH_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      matrix:
        os: [ "buster", "bullseye" ]
        version: [ "13", "14", "15", "16" ]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v2
      - run: curl -sSLf https://raw.githubusercontent.com/octohelm/wagon/main/install.sh | sudo sh

      - run: make ship.${{ matrix.os }} VERSION=${{ matrix.version }}
